version: '2'
services:
    db:
        scale: 1
        start_on_create: true
        health_check:
            healthy_threshold: 2
            response_timeout: 2000
            port: 5432
            unhealthy_threshold: 3
            initializing_timeout: 60000
            interval: 2000
            strategy: recreate
            reinitializing_timeout: 60000
    db-dump:
        scale: 1
        start_on_create: false